language: node_js
node_js:
- 16.16.0
cache:
  directories:
  - node_modules
services:
- mongodb
install:
- npm ci
script:
- npm test
before_deploy:
- rvm $(travis_internal_ruby) --fuzzy do ruby -S gem install faraday -v 1.8.0